name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure (CMake)
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DBUILD_STATIC=ON \
            -DBUILD_SHARED=ON \
            -DBUILD_TESTS=ON

      - name: Build static lib
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --target secp256k1-wrapper-static -- -j2

      - name: Build shared lib
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --target secp256k1-wrapper-shared -- -j2

      - name: Build tests
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --target test_wrapper -- -j2
        
      - name: Test
        run: ctest --test-dir build -C ${{ env.BUILD_TYPE }} --output-on-failure
