name: CMake (static only)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make gcc

      - name: Configure CMake (static only)
        run: |
          cmake -B ${{ github.workspace }}/build \
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                -DBUILD_TESTS=ON \
                -DBUILD_EXAMPLES=OFF \
                -DBUILD_STATIC=ON \
                -DBUILD_SHARED=OFF

      - name: Build static library
        run: |
          cmake --build ${{ github.workspace }}/build \
                --config ${{ env.BUILD_TYPE }} \
                --target secp256k1-wrapper-static \
                -- -j2

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ env.BUILD_TYPE }} --output-on-failure
